### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by MMachor** [libimobiledevice/libplist#36] opened 2014-07-08 18:18 UTC
I am having the following issue when running make on the libplist.  ./autogen.sh --without-cython completes successfully, but then I encounter this when I run make.  This is on a WIndows 7 machine using MinGW-32 as the cross compiler.  Any help appreciated.

![error](https://cloud.githubusercontent.com/assets/5774228/3514450/2a8e7c94-06cc-11e4-8674-ba3c834ed0e6.png)

**Comment by qmfrederik** [comment] 2015-01-16 16:51
Hi,

We got libimobiledevice to compile on Windows using MinGW. Since a lot of people seem to have issues compiling it, we've created a binary distribution of MinGW for Windows.

You can find the binary files [here](http://quamotion.mobi/iMobileDevice/Download)

If you want to compile from source yourself, you can download all the packages with the source files from [our website](http://quamotion.mobi/iMobileDevice/Article/version). Most of them come straight from the libimobiledevice repos; some small patches were required and we published them [on our GitHub repository](http://github.com/quamotion).

Hope it helps,

Frederik

**Comment by nikias** [comment] 2016-10-05 19:39
Closing. This is not a bug in libplist anyway.

**Closed by nikias** 2016-10-05 19:39 UTC
Labels: question
